# Generated by Django 5.2.14 on 2026-06-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('arrived', 'Arrived'), ('in_service', 'In Service'), ('completed', 'Completed'), ('invoiced', 'Invoiced'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='requested', max_length=32)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('receptionist', 'Receptionist')], default='customer', max_length=32)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('no_show_reason', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customerprofile')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='employees.employeeprofile')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_at_booking', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_services', to='appointments.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
