export const ROUTES = {
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  accounts: "/accounts",
  customers: "/customers",
  employees: "/employees",
  services: "/services",
  appointments: "/appointments",
  serviceExecutions: "/service-executions",
  invoices: "/invoices",
  payments: "/payments",
  promotions: "/promotions",
  vouchers: "/vouchers",
  rewards: "/rewards",
  feedback: "/feedback",
  complaints: "/complaints",
  notifications: "/notifications",
  reports: "/reports",
  forbidden: "/403",
  notFound: "/404",
} as const;
