export const STATUS_COLORS: Record<string, string> = {
  active: "green",
  inactive: "default",
  archived: "red",
  requested: "blue",
  confirmed: "green",
  arrived: "cyan",
  in_service: "purple",
  completed: "gold",
  invoiced: "gold",
  closed: "default",
  cancelled: "red",
  no_show: "volcano",
  draft: "default",
  issued: "blue",
  partially_paid: "orange",
  paid: "green",
  adjusted: "purple",
  attempted: "default",
  pending: "orange",
  successful: "green",
  failed: "red",
  refunded: "orange",
  received: "blue",
  responded: "green",
  assigned: "cyan",
  in_review: "purple",
  escalated: "volcano",
  resolved: "green",
  read: "default",
  delivered: "green",
  created: "blue",
};

export const formatStatusLabel = (status?: string) =>
  status ? status.replace(/_/g, " ").replace(/\b\w/g, (char: string) => char.toUpperCase()) : "Unknown";
